### ISSUE TITLE
Can't enable JSComments

### ISSUE THREAD

**Issue by offray** [nunopress/grav-plugin-jscomments#8]
Hi,

I'm using grav v0.9.45 and  JSComments v1.2.10, but until now I can't make the plugin work. This were my steps:

1. Installing it from GPM, 
2. Configuring it from admin panel,
3. Enabling twig process by modifying `user/config/system.yaml` with:

      process:
        markdown: true
        twig: true
4. Modifying `user/themes/notepad/templates/post.html.twig` with:

        <article class="summer-post-content post">
          <div>
            {{ content }}
           <br>
            {{ jscomments('disqus', { shortname: mutabit }) }}
          </div>
        </article>
5. I only get "Blog Comments Powered by Disqus", but no actual  forms for discussion. 

I will explore some self-hosted commenting systems like [isso](http://posativ.org/isso/) meanwhile, until I know what I'm missing... should be easier. By the way, I'm blogging about my experience with grav compared with Nikola here: 

http://mutabit.com/offray/blog/en/entry/2015-10-06-grav-nikola-both 

but you can't comment there directly :-P

**Comment by offray** [comment]
I solved it by adding the "Universal Code" provided by discuss to the `user/themes/notepad/templates/post.html.twig`. Seems easier that the plugin method.

**Comment by Magew** [comment]
Can someone provide what the fix was? I can't seem to get the ability to comment to show up either.

**Comment by offray** [comment]
@Magew go to `user/<your-template-name>/templates/post.html.twig` and add the "Universal Code" from the Disqus provided options at that template. If you have any more specific questions on what is not clear, let us know.
